// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ai/inworld/studio/v1alpha/behavioral_contexts.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ai.Inworld.Studio.V1Alpha {

  /// <summary>Holder for reflection information generated from ai/inworld/studio/v1alpha/behavioral_contexts.proto</summary>
  public static partial class BehavioralContextsReflection {

    #region Descriptor
    /// <summary>File descriptor for ai/inworld/studio/v1alpha/behavioral_contexts.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    /*
    static BehavioralContextsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjNhaS9pbndvcmxkL3N0dWRpby92MWFscGhhL2JlaGF2aW9yYWxfY29udGV4",
            "dHMucHJvdG8SGWFpLmlud29ybGQuc3R1ZGlvLnYxYWxwaGEaH2dvb2dsZS9h",
            "cGkvZmllbGRfYmVoYXZpb3IucHJvdG8aGWdvb2dsZS9hcGkvcmVzb3VyY2Uu",
            "cHJvdG8iXwobQmVoYXZpb3JhbENvbnRleHRQcm9wZXJ0aWVzEhoKEnN0YXJ0",
            "X2NvbnZlcnNhdGlvbhgBIAEoCBIQCghwcmlvcml0eRgCIAEoBRISCgppc19k",
            "ZWZhdWx0GAMgASgIIjAKGlRlbGxFeGFjdFRleHRDb250ZXh0QWN0aW9uEhIK",
            "CmV4YWN0X3RleHQYASABKAkiOQobVGVsbEluc3RydWN0ZWRDb250ZXh0QWN0",
            "aW9uEhoKEnNwZWVjaF9pbnN0cnVjdGlvbhgBIAEoCSI0ChxTZW5kQ3VzdG9t",
            "RXZlbnRDb250ZXh0QWN0aW9uEhQKDGN1c3RvbV9ldmVudBgBIAEoCSJRChdT",
            "ZXRFbW90aW9uQ29udGV4dEFjdGlvbhI2CghiZWhhdmlvchgBIAEoDjIkLmFp",
            "Lmlud29ybGQuc3R1ZGlvLnYxYWxwaGEuU3BhZmZDb2RlIvICChdCZWhhdmlv",
            "cmFsQ29udGV4dEFjdGlvbhIMCgR1dWlkGAEgASgJEksKCnRlbGxfZXhhY3QY",
            "AiABKAsyNS5haS5pbndvcmxkLnN0dWRpby52MWFscGhhLlRlbGxFeGFjdFRl",
            "eHRDb250ZXh0QWN0aW9uSAASUQoPdGVsbF9pbnN0cnVjdGVkGAMgASgLMjYu",
            "YWkuaW53b3JsZC5zdHVkaW8udjFhbHBoYS5UZWxsSW5zdHJ1Y3RlZENvbnRl",
            "eHRBY3Rpb25IABJUChFzZW5kX2N1c3RvbV9ldmVudBgEIAEoCzI3LmFpLmlu",
            "d29ybGQuc3R1ZGlvLnYxYWxwaGEuU2VuZEN1c3RvbUV2ZW50Q29udGV4dEFj",
            "dGlvbkgAEkkKC3NldF9lbW90aW9uGAUgASgLMjIuYWkuaW53b3JsZC5zdHVk",
            "aW8udjFhbHBoYS5TZXRFbW90aW9uQ29udGV4dEFjdGlvbkgAQggKBmFjdGlv",
            "biLIAQocQmVoYXZpb3JhbENvbnRleHRJbnRlcmFjdGlvbhJVChBpbnRlcmFj",
            "dGlvbl90eXBlGAEgASgOMjsuYWkuaW53b3JsZC5zdHVkaW8udjFhbHBoYS5C",
            "ZWhhdmlvcmFsQ29udGV4dEludGVyYWN0aW9uVHlwZRJDCgdhY3Rpb25zGAIg",
            "AygLMjIuYWkuaW53b3JsZC5zdHVkaW8udjFhbHBoYS5CZWhhdmlvcmFsQ29u",
            "dGV4dEFjdGlvbhIMCgR1dWlkGAMgASgJIpQDChFCZWhhdmlvcmFsQ29udGV4",
            "dBIMCgRuYW1lGAEgASgJEhIKCm1vdGl2YXRpb24YAiABKAkSSgoKcHJvcGVy",
            "dGllcxgDIAEoCzI2LmFpLmlud29ybGQuc3R1ZGlvLnYxYWxwaGEuQmVoYXZp",
            "b3JhbENvbnRleHRQcm9wZXJ0aWVzEjAKCHRyaWdnZXJzGAQgAygJQh7gQQL6",
            "QRgKFmFwaS5pbndvcmxkLmFpL1RyaWdnZXISXwoeYmVoYXZpb3JhbF9jb250",
            "ZXh0X2ludGVyYWN0aW9uGAUgAygLMjcuYWkuaW53b3JsZC5zdHVkaW8udjFh",
            "bHBoYS5CZWhhdmlvcmFsQ29udGV4dEludGVyYWN0aW9uOn7qQXsKIGFwaS5p",
            "bndvcmxkLmFpL0JlaGF2aW9yYWxDb250ZXh0Eld3b3Jrc3BhY2VzL3t3b3Jr",
            "c3BhY2V9L2NoYXJhY3RlcnMve2NoYXJhY3Rlcn0vYmVoYXZpb3JhbC1jb250",
            "ZXh0cy97YmVoYXZpb3JhbC1jb250ZXh0c30qkQEKIEJlaGF2aW9yYWxDb250",
            "ZXh0SW50ZXJhY3Rpb25UeXBlEjMKL0JFSEFWSU9SQUxfQ09OVEVYVF9JTlRF",
            "UkFDVElPTl9UWVBFX1VOU1BFQ0lGSUVEEAASOAo0QkVIQVZJT1JBTF9DT05U",
            "RVhUX0lOVEVSQUNUSU9OX1RZUEVfRVhFQ1VURV9TRVFVRU5DRRABKrgCCglT",
            "cGFmZkNvZGUSGgoWU1BBRkZfQ09ERV9VTlNQRUNJRklFRBAAEgsKB05FVVRS",
            "QUwQARILCgdESVNHVVNUEAISDAoIQ09OVEVNUFQQAxIQCgxCRUxMSUdFUkVO",
            "Q0UQBBIPCgtET01JTkVFUklORxAFEg0KCUNSSVRJQ0lTTRAGEgkKBUFOR0VS",
            "EAcSCwoHVEVOU0lPThAIEg8KC1RFTlNFX0hVTU9SEAkSEQoNREVGRU5TSVZF",
            "TkVTUxAKEgsKB1dISU5JTkcQCxILCgdTQURORVNTEAwSEAoMU1RPTkVXQUxM",
            "SU5HEA0SDAoISU5URVJFU1QQDhIOCgpWQUxJREFUSU9OEA8SDQoJQUZGRUNU",
            "SU9OEBASCQoFSFVNT1IQERIMCghTVVJQUklTRRASEgcKA0pPWRATQqEBChlh",
            "aS5pbndvcmxkLnN0dWRpby52MWFscGhhQhdCZWhhdmlvcmFsQ29udGV4dHNQ",
            "cm90b1ABWk1naXRodWIuY29tL2lud29ybGQtYWkvaW53b3JsZC9zZXJ2aW5n",
            "L2dycGMtZ2F0ZXdheS9idWlsZC9wcm90by9zdHVkaW8vdjFhbHBoYaoCGUFp",
            "Lklud29ybGQuU3R1ZGlvLlYxQWxwaGFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.FieldBehaviorReflection.Descriptor, global::Google.Api.ResourceReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Ai.Inworld.Studio.V1Alpha.BehavioralContextInteractionType), typeof(global::Ai.Inworld.Studio.V1Alpha.SpaffCode), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ai.Inworld.Studio.V1Alpha.BehavioralContextProperties), global::Ai.Inworld.Studio.V1Alpha.BehavioralContextProperties.Parser, new[]{ "StartConversation", "Priority", "IsDefault" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ai.Inworld.Studio.V1Alpha.TellExactTextContextAction), global::Ai.Inworld.Studio.V1Alpha.TellExactTextContextAction.Parser, new[]{ "ExactText" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ai.Inworld.Studio.V1Alpha.TellInstructedContextAction), global::Ai.Inworld.Studio.V1Alpha.TellInstructedContextAction.Parser, new[]{ "SpeechInstruction" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ai.Inworld.Studio.V1Alpha.SendCustomEventContextAction), global::Ai.Inworld.Studio.V1Alpha.SendCustomEventContextAction.Parser, new[]{ "CustomEvent" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ai.Inworld.Studio.V1Alpha.SetEmotionContextAction), global::Ai.Inworld.Studio.V1Alpha.SetEmotionContextAction.Parser, new[]{ "Behavior" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ai.Inworld.Studio.V1Alpha.BehavioralContextAction), global::Ai.Inworld.Studio.V1Alpha.BehavioralContextAction.Parser, new[]{ "Uuid", "TellExact", "TellInstructed", "SendCustomEvent", "SetEmotion" }, new[]{ "Action" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ai.Inworld.Studio.V1Alpha.BehavioralContextInteraction), global::Ai.Inworld.Studio.V1Alpha.BehavioralContextInteraction.Parser, new[]{ "InteractionType", "Actions", "Uuid" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ai.Inworld.Studio.V1Alpha.BehavioralContext), global::Ai.Inworld.Studio.V1Alpha.BehavioralContext.Parser, new[]{ "Name", "Motivation", "Properties", "Triggers", "BehavioralContextInteraction" }, null, null, null, null)
          }));
    }*/
    #endregion

  }
  #region Enums
  /// <summary>
  /// Enum representing the type of the resource to generate resource name for.
  /// </summary>
  public enum BehavioralContextInteractionType {
    /// <summary>
    /// The behavioral context interaction type type is not specified.
    /// </summary>
    [pbr::OriginalName("BEHAVIORAL_CONTEXT_INTERACTION_TYPE_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// During this type of interaction character will sequentially execute sequence of actions.
    /// </summary>
    [pbr::OriginalName("BEHAVIORAL_CONTEXT_INTERACTION_TYPE_EXECUTE_SEQUENCE")] ExecuteSequence = 1,
  }

  /// <summary>
  /// Emotional behavior codes
  /// </summary>
  public enum SpaffCode {
    /// <summary>
    /// staff code unspecified
    /// </summary>
    [pbr::OriginalName("SPAFF_CODE_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// neutral
    /// </summary>
    [pbr::OriginalName("NEUTRAL")] Neutral = 1,
    /// <summary>
    /// disgust
    /// </summary>
    [pbr::OriginalName("DISGUST")] Disgust = 2,
    /// <summary>
    /// contempt
    /// </summary>
    [pbr::OriginalName("CONTEMPT")] Contempt = 3,
    /// <summary>
    /// belligerence
    /// </summary>
    [pbr::OriginalName("BELLIGERENCE")] Belligerence = 4,
    /// <summary>
    /// domineering
    /// </summary>
    [pbr::OriginalName("DOMINEERING")] Domineering = 5,
    /// <summary>
    /// criticism
    /// </summary>
    [pbr::OriginalName("CRITICISM")] Criticism = 6,
    /// <summary>
    /// anger
    /// </summary>
    [pbr::OriginalName("ANGER")] Anger = 7,
    /// <summary>
    /// tension
    /// </summary>
    [pbr::OriginalName("TENSION")] Tension = 8,
    /// <summary>
    /// tense_humor
    /// </summary>
    [pbr::OriginalName("TENSE_HUMOR")] TenseHumor = 9,
    /// <summary>
    /// defensiveness
    /// </summary>
    [pbr::OriginalName("DEFENSIVENESS")] Defensiveness = 10,
    /// <summary>
    /// whining
    /// </summary>
    [pbr::OriginalName("WHINING")] Whining = 11,
    /// <summary>
    /// sadness
    /// </summary>
    [pbr::OriginalName("SADNESS")] Sadness = 12,
    /// <summary>
    /// stonewalling
    /// </summary>
    [pbr::OriginalName("STONEWALLING")] Stonewalling = 13,
    /// <summary>
    /// interest
    /// </summary>
    [pbr::OriginalName("INTEREST")] Interest = 14,
    /// <summary>
    /// validation
    /// </summary>
    [pbr::OriginalName("VALIDATION")] Validation = 15,
    /// <summary>
    /// affection
    /// </summary>
    [pbr::OriginalName("AFFECTION")] Affection = 16,
    /// <summary>
    /// humor
    /// </summary>
    [pbr::OriginalName("HUMOR")] Humor = 17,
    /// <summary>
    /// surprise
    /// </summary>
    [pbr::OriginalName("SURPRISE")] Surprise = 18,
    /// <summary>
    /// joy
    /// </summary>
    [pbr::OriginalName("JOY")] Joy = 19,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Additional behavioral context properties of the context.
  /// </summary>
  public sealed partial class BehavioralContextProperties : pb::IMessage<BehavioralContextProperties>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BehavioralContextProperties> _parser = new pb::MessageParser<BehavioralContextProperties>(() => new BehavioralContextProperties());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BehavioralContextProperties> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ai.Inworld.Studio.V1Alpha.BehavioralContextsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BehavioralContextProperties() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BehavioralContextProperties(BehavioralContextProperties other) : this() {
      startConversation_ = other.startConversation_;
      priority_ = other.priority_;
      isDefault_ = other.isDefault_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BehavioralContextProperties Clone() {
      return new BehavioralContextProperties(this);
    }

    /// <summary>Field number for the "start_conversation" field.</summary>
    public const int StartConversationFieldNumber = 1;
    private bool startConversation_;
    /// <summary>
    /// If start execution of corresponding context right after all triggers was received.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool StartConversation {
      get { return startConversation_; }
      set {
        startConversation_ = value;
      }
    }

    /// <summary>Field number for the "priority" field.</summary>
    public const int PriorityFieldNumber = 2;
    private int priority_;
    /// <summary>
    /// Regulates order of context execution in case multiple contexts are active at the same time.
    /// The lesser the number the more priority will have this exact context. Default value is 100.
    /// if two context will have the same priority - no particular execution order is guaranteed.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Priority {
      get { return priority_; }
      set {
        priority_ = value;
      }
    }

    /// <summary>Field number for the "is_default" field.</summary>
    public const int IsDefaultFieldNumber = 3;
    private bool isDefault_;
    /// <summary>
    /// If activate this context as default (do not check its triggers at the conversation
    /// start). It  should be set True only for one context.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsDefault {
      get { return isDefault_; }
      set {
        isDefault_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BehavioralContextProperties);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BehavioralContextProperties other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StartConversation != other.StartConversation) return false;
      if (Priority != other.Priority) return false;
      if (IsDefault != other.IsDefault) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (StartConversation != false) hash ^= StartConversation.GetHashCode();
      if (Priority != 0) hash ^= Priority.GetHashCode();
      if (IsDefault != false) hash ^= IsDefault.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StartConversation != false) {
        output.WriteRawTag(8);
        output.WriteBool(StartConversation);
      }
      if (Priority != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Priority);
      }
      if (IsDefault != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsDefault);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StartConversation != false) {
        output.WriteRawTag(8);
        output.WriteBool(StartConversation);
      }
      if (Priority != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Priority);
      }
      if (IsDefault != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsDefault);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (StartConversation != false) {
        size += 1 + 1;
      }
      if (Priority != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Priority);
      }
      if (IsDefault != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BehavioralContextProperties other) {
      if (other == null) {
        return;
      }
      if (other.StartConversation != false) {
        StartConversation = other.StartConversation;
      }
      if (other.Priority != 0) {
        Priority = other.Priority;
      }
      if (other.IsDefault != false) {
        IsDefault = other.IsDefault;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StartConversation = input.ReadBool();
            break;
          }
          case 16: {
            Priority = input.ReadInt32();
            break;
          }
          case 24: {
            IsDefault = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            StartConversation = input.ReadBool();
            break;
          }
          case 16: {
            Priority = input.ReadInt32();
            break;
          }
          case 24: {
            IsDefault = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// When executing, character will tell exactly what is defined in this action.
  /// </summary>
  public sealed partial class TellExactTextContextAction : pb::IMessage<TellExactTextContextAction>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TellExactTextContextAction> _parser = new pb::MessageParser<TellExactTextContextAction>(() => new TellExactTextContextAction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TellExactTextContextAction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ai.Inworld.Studio.V1Alpha.BehavioralContextsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TellExactTextContextAction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TellExactTextContextAction(TellExactTextContextAction other) : this() {
      exactText_ = other.exactText_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TellExactTextContextAction Clone() {
      return new TellExactTextContextAction(this);
    }

    /// <summary>Field number for the "exact_text" field.</summary>
    public const int ExactTextFieldNumber = 1;
    private string exactText_ = "";
    /// <summary>
    /// The exact text that should be spoken.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ExactText {
      get { return exactText_; }
      set {
        exactText_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TellExactTextContextAction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TellExactTextContextAction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ExactText != other.ExactText) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ExactText.Length != 0) hash ^= ExactText.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ExactText.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ExactText);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ExactText.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ExactText);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ExactText.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExactText);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TellExactTextContextAction other) {
      if (other == null) {
        return;
      }
      if (other.ExactText.Length != 0) {
        ExactText = other.ExactText;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ExactText = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ExactText = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// When executing this action character will generate reply based on provided instruction.
  /// </summary>
  public sealed partial class TellInstructedContextAction : pb::IMessage<TellInstructedContextAction>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TellInstructedContextAction> _parser = new pb::MessageParser<TellInstructedContextAction>(() => new TellInstructedContextAction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TellInstructedContextAction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ai.Inworld.Studio.V1Alpha.BehavioralContextsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TellInstructedContextAction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TellInstructedContextAction(TellInstructedContextAction other) : this() {
      speechInstruction_ = other.speechInstruction_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TellInstructedContextAction Clone() {
      return new TellInstructedContextAction(this);
    }

    /// <summary>Field number for the "speech_instruction" field.</summary>
    public const int SpeechInstructionFieldNumber = 1;
    private string speechInstruction_ = "";
    /// <summary>
    /// Instruction on what player wants to tell, how they wants to reply.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SpeechInstruction {
      get { return speechInstruction_; }
      set {
        speechInstruction_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TellInstructedContextAction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TellInstructedContextAction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SpeechInstruction != other.SpeechInstruction) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SpeechInstruction.Length != 0) hash ^= SpeechInstruction.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SpeechInstruction.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SpeechInstruction);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SpeechInstruction.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SpeechInstruction);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SpeechInstruction.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SpeechInstruction);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TellInstructedContextAction other) {
      if (other == null) {
        return;
      }
      if (other.SpeechInstruction.Length != 0) {
        SpeechInstruction = other.SpeechInstruction;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SpeechInstruction = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SpeechInstruction = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// When executing, character will send given custom event to the platform.
  /// </summary>
  public sealed partial class SendCustomEventContextAction : pb::IMessage<SendCustomEventContextAction>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SendCustomEventContextAction> _parser = new pb::MessageParser<SendCustomEventContextAction>(() => new SendCustomEventContextAction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SendCustomEventContextAction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ai.Inworld.Studio.V1Alpha.BehavioralContextsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SendCustomEventContextAction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SendCustomEventContextAction(SendCustomEventContextAction other) : this() {
      customEvent_ = other.customEvent_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SendCustomEventContextAction Clone() {
      return new SendCustomEventContextAction(this);
    }

    /// <summary>Field number for the "custom_event" field.</summary>
    public const int CustomEventFieldNumber = 1;
    private string customEvent_ = "";
    /// <summary>
    /// Name of the custom_event to send to return from the brain.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CustomEvent {
      get { return customEvent_; }
      set {
        customEvent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SendCustomEventContextAction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SendCustomEventContextAction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CustomEvent != other.CustomEvent) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CustomEvent.Length != 0) hash ^= CustomEvent.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CustomEvent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CustomEvent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CustomEvent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CustomEvent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CustomEvent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CustomEvent);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SendCustomEventContextAction other) {
      if (other == null) {
        return;
      }
      if (other.CustomEvent.Length != 0) {
        CustomEvent = other.CustomEvent;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CustomEvent = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CustomEvent = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Sets/modifies emotional state of the character
  /// </summary>
  public sealed partial class SetEmotionContextAction : pb::IMessage<SetEmotionContextAction>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SetEmotionContextAction> _parser = new pb::MessageParser<SetEmotionContextAction>(() => new SetEmotionContextAction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SetEmotionContextAction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ai.Inworld.Studio.V1Alpha.BehavioralContextsReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SetEmotionContextAction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SetEmotionContextAction(SetEmotionContextAction other) : this() {
      behavior_ = other.behavior_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SetEmotionContextAction Clone() {
      return new SetEmotionContextAction(this);
    }

    /// <summary>Field number for the "behavior" field.</summary>
    public const int BehaviorFieldNumber = 1;
    private global::Ai.Inworld.Studio.V1Alpha.SpaffCode behavior_ = global::Ai.Inworld.Studio.V1Alpha.SpaffCode.Unspecified;
    /// <summary>
    /// Current format of emotions in this place need to be discussed further.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ai.Inworld.Studio.V1Alpha.SpaffCode Behavior {
      get { return behavior_; }
      set {
        behavior_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SetEmotionContextAction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SetEmotionContextAction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Behavior != other.Behavior) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Behavior != global::Ai.Inworld.Studio.V1Alpha.SpaffCode.Unspecified) hash ^= Behavior.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Behavior != global::Ai.Inworld.Studio.V1Alpha.SpaffCode.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Behavior);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Behavior != global::Ai.Inworld.Studio.V1Alpha.SpaffCode.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Behavior);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Behavior != global::Ai.Inworld.Studio.V1Alpha.SpaffCode.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Behavior);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SetEmotionContextAction other) {
      if (other == null) {
        return;
      }
      if (other.Behavior != global::Ai.Inworld.Studio.V1Alpha.SpaffCode.Unspecified) {
        Behavior = other.Behavior;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Behavior = (global::Ai.Inworld.Studio.V1Alpha.SpaffCode) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Behavior = (global::Ai.Inworld.Studio.V1Alpha.SpaffCode) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Single action that are executed during an interaction.
  /// </summary>
  public sealed partial class BehavioralContextAction : pb::IMessage<BehavioralContextAction>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BehavioralContextAction> _parser = new pb::MessageParser<BehavioralContextAction>(() => new BehavioralContextAction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BehavioralContextAction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ai.Inworld.Studio.V1Alpha.BehavioralContextsReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BehavioralContextAction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BehavioralContextAction(BehavioralContextAction other) : this() {
      uuid_ = other.uuid_;
      switch (other.ActionCase) {
        case ActionOneofCase.TellExact:
          TellExact = other.TellExact.Clone();
          break;
        case ActionOneofCase.TellInstructed:
          TellInstructed = other.TellInstructed.Clone();
          break;
        case ActionOneofCase.SendCustomEvent:
          SendCustomEvent = other.SendCustomEvent.Clone();
          break;
        case ActionOneofCase.SetEmotion:
          SetEmotion = other.SetEmotion.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BehavioralContextAction Clone() {
      return new BehavioralContextAction(this);
    }

    /// <summary>Field number for the "uuid" field.</summary>
    public const int UuidFieldNumber = 1;
    private string uuid_ = "";
    /// <summary>
    /// Unique (throughout the entire service) universally unique identifier
    /// automatically generated by system.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Uuid {
      get { return uuid_; }
      set {
        uuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tell_exact" field.</summary>
    public const int TellExactFieldNumber = 2;
    /// <summary>
    /// When executing, character will tell exactly what is defined in this action.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ai.Inworld.Studio.V1Alpha.TellExactTextContextAction TellExact {
      get { return actionCase_ == ActionOneofCase.TellExact ? (global::Ai.Inworld.Studio.V1Alpha.TellExactTextContextAction) action_ : null; }
      set {
        action_ = value;
        actionCase_ = value == null ? ActionOneofCase.None : ActionOneofCase.TellExact;
      }
    }

    /// <summary>Field number for the "tell_instructed" field.</summary>
    public const int TellInstructedFieldNumber = 3;
    /// <summary>
    /// When executing this action character will generate reply based on provided instruction.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ai.Inworld.Studio.V1Alpha.TellInstructedContextAction TellInstructed {
      get { return actionCase_ == ActionOneofCase.TellInstructed ? (global::Ai.Inworld.Studio.V1Alpha.TellInstructedContextAction) action_ : null; }
      set {
        action_ = value;
        actionCase_ = value == null ? ActionOneofCase.None : ActionOneofCase.TellInstructed;
      }
    }

    /// <summary>Field number for the "send_custom_event" field.</summary>
    public const int SendCustomEventFieldNumber = 4;
    /// <summary>
    /// When executing, character will send given custom event to the platform.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ai.Inworld.Studio.V1Alpha.SendCustomEventContextAction SendCustomEvent {
      get { return actionCase_ == ActionOneofCase.SendCustomEvent ? (global::Ai.Inworld.Studio.V1Alpha.SendCustomEventContextAction) action_ : null; }
      set {
        action_ = value;
        actionCase_ = value == null ? ActionOneofCase.None : ActionOneofCase.SendCustomEvent;
      }
    }

    /// <summary>Field number for the "set_emotion" field.</summary>
    public const int SetEmotionFieldNumber = 5;
    /// <summary>
    /// Emotion specific action
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ai.Inworld.Studio.V1Alpha.SetEmotionContextAction SetEmotion {
      get { return actionCase_ == ActionOneofCase.SetEmotion ? (global::Ai.Inworld.Studio.V1Alpha.SetEmotionContextAction) action_ : null; }
      set {
        action_ = value;
        actionCase_ = value == null ? ActionOneofCase.None : ActionOneofCase.SetEmotion;
      }
    }

    private object action_;
    /// <summary>Enum of possible cases for the "action" oneof.</summary>
    public enum ActionOneofCase {
      None = 0,
      TellExact = 2,
      TellInstructed = 3,
      SendCustomEvent = 4,
      SetEmotion = 5,
    }
    private ActionOneofCase actionCase_ = ActionOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionOneofCase ActionCase {
      get { return actionCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAction() {
      actionCase_ = ActionOneofCase.None;
      action_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BehavioralContextAction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BehavioralContextAction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uuid != other.Uuid) return false;
      if (!object.Equals(TellExact, other.TellExact)) return false;
      if (!object.Equals(TellInstructed, other.TellInstructed)) return false;
      if (!object.Equals(SendCustomEvent, other.SendCustomEvent)) return false;
      if (!object.Equals(SetEmotion, other.SetEmotion)) return false;
      if (ActionCase != other.ActionCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Uuid.Length != 0) hash ^= Uuid.GetHashCode();
      if (actionCase_ == ActionOneofCase.TellExact) hash ^= TellExact.GetHashCode();
      if (actionCase_ == ActionOneofCase.TellInstructed) hash ^= TellInstructed.GetHashCode();
      if (actionCase_ == ActionOneofCase.SendCustomEvent) hash ^= SendCustomEvent.GetHashCode();
      if (actionCase_ == ActionOneofCase.SetEmotion) hash ^= SetEmotion.GetHashCode();
      hash ^= (int) actionCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Uuid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Uuid);
      }
      if (actionCase_ == ActionOneofCase.TellExact) {
        output.WriteRawTag(18);
        output.WriteMessage(TellExact);
      }
      if (actionCase_ == ActionOneofCase.TellInstructed) {
        output.WriteRawTag(26);
        output.WriteMessage(TellInstructed);
      }
      if (actionCase_ == ActionOneofCase.SendCustomEvent) {
        output.WriteRawTag(34);
        output.WriteMessage(SendCustomEvent);
      }
      if (actionCase_ == ActionOneofCase.SetEmotion) {
        output.WriteRawTag(42);
        output.WriteMessage(SetEmotion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Uuid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Uuid);
      }
      if (actionCase_ == ActionOneofCase.TellExact) {
        output.WriteRawTag(18);
        output.WriteMessage(TellExact);
      }
      if (actionCase_ == ActionOneofCase.TellInstructed) {
        output.WriteRawTag(26);
        output.WriteMessage(TellInstructed);
      }
      if (actionCase_ == ActionOneofCase.SendCustomEvent) {
        output.WriteRawTag(34);
        output.WriteMessage(SendCustomEvent);
      }
      if (actionCase_ == ActionOneofCase.SetEmotion) {
        output.WriteRawTag(42);
        output.WriteMessage(SetEmotion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Uuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uuid);
      }
      if (actionCase_ == ActionOneofCase.TellExact) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TellExact);
      }
      if (actionCase_ == ActionOneofCase.TellInstructed) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TellInstructed);
      }
      if (actionCase_ == ActionOneofCase.SendCustomEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SendCustomEvent);
      }
      if (actionCase_ == ActionOneofCase.SetEmotion) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SetEmotion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BehavioralContextAction other) {
      if (other == null) {
        return;
      }
      if (other.Uuid.Length != 0) {
        Uuid = other.Uuid;
      }
      switch (other.ActionCase) {
        case ActionOneofCase.TellExact:
          if (TellExact == null) {
            TellExact = new global::Ai.Inworld.Studio.V1Alpha.TellExactTextContextAction();
          }
          TellExact.MergeFrom(other.TellExact);
          break;
        case ActionOneofCase.TellInstructed:
          if (TellInstructed == null) {
            TellInstructed = new global::Ai.Inworld.Studio.V1Alpha.TellInstructedContextAction();
          }
          TellInstructed.MergeFrom(other.TellInstructed);
          break;
        case ActionOneofCase.SendCustomEvent:
          if (SendCustomEvent == null) {
            SendCustomEvent = new global::Ai.Inworld.Studio.V1Alpha.SendCustomEventContextAction();
          }
          SendCustomEvent.MergeFrom(other.SendCustomEvent);
          break;
        case ActionOneofCase.SetEmotion:
          if (SetEmotion == null) {
            SetEmotion = new global::Ai.Inworld.Studio.V1Alpha.SetEmotionContextAction();
          }
          SetEmotion.MergeFrom(other.SetEmotion);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Uuid = input.ReadString();
            break;
          }
          case 18: {
            global::Ai.Inworld.Studio.V1Alpha.TellExactTextContextAction subBuilder = new global::Ai.Inworld.Studio.V1Alpha.TellExactTextContextAction();
            if (actionCase_ == ActionOneofCase.TellExact) {
              subBuilder.MergeFrom(TellExact);
            }
            input.ReadMessage(subBuilder);
            TellExact = subBuilder;
            break;
          }
          case 26: {
            global::Ai.Inworld.Studio.V1Alpha.TellInstructedContextAction subBuilder = new global::Ai.Inworld.Studio.V1Alpha.TellInstructedContextAction();
            if (actionCase_ == ActionOneofCase.TellInstructed) {
              subBuilder.MergeFrom(TellInstructed);
            }
            input.ReadMessage(subBuilder);
            TellInstructed = subBuilder;
            break;
          }
          case 34: {
            global::Ai.Inworld.Studio.V1Alpha.SendCustomEventContextAction subBuilder = new global::Ai.Inworld.Studio.V1Alpha.SendCustomEventContextAction();
            if (actionCase_ == ActionOneofCase.SendCustomEvent) {
              subBuilder.MergeFrom(SendCustomEvent);
            }
            input.ReadMessage(subBuilder);
            SendCustomEvent = subBuilder;
            break;
          }
          case 42: {
            global::Ai.Inworld.Studio.V1Alpha.SetEmotionContextAction subBuilder = new global::Ai.Inworld.Studio.V1Alpha.SetEmotionContextAction();
            if (actionCase_ == ActionOneofCase.SetEmotion) {
              subBuilder.MergeFrom(SetEmotion);
            }
            input.ReadMessage(subBuilder);
            SetEmotion = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Uuid = input.ReadString();
            break;
          }
          case 18: {
            global::Ai.Inworld.Studio.V1Alpha.TellExactTextContextAction subBuilder = new global::Ai.Inworld.Studio.V1Alpha.TellExactTextContextAction();
            if (actionCase_ == ActionOneofCase.TellExact) {
              subBuilder.MergeFrom(TellExact);
            }
            input.ReadMessage(subBuilder);
            TellExact = subBuilder;
            break;
          }
          case 26: {
            global::Ai.Inworld.Studio.V1Alpha.TellInstructedContextAction subBuilder = new global::Ai.Inworld.Studio.V1Alpha.TellInstructedContextAction();
            if (actionCase_ == ActionOneofCase.TellInstructed) {
              subBuilder.MergeFrom(TellInstructed);
            }
            input.ReadMessage(subBuilder);
            TellInstructed = subBuilder;
            break;
          }
          case 34: {
            global::Ai.Inworld.Studio.V1Alpha.SendCustomEventContextAction subBuilder = new global::Ai.Inworld.Studio.V1Alpha.SendCustomEventContextAction();
            if (actionCase_ == ActionOneofCase.SendCustomEvent) {
              subBuilder.MergeFrom(SendCustomEvent);
            }
            input.ReadMessage(subBuilder);
            SendCustomEvent = subBuilder;
            break;
          }
          case 42: {
            global::Ai.Inworld.Studio.V1Alpha.SetEmotionContextAction subBuilder = new global::Ai.Inworld.Studio.V1Alpha.SetEmotionContextAction();
            if (actionCase_ == ActionOneofCase.SetEmotion) {
              subBuilder.MergeFrom(SetEmotion);
            }
            input.ReadMessage(subBuilder);
            SetEmotion = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Single action that are executed during an interaction.
  /// </summary>
  public sealed partial class BehavioralContextInteraction : pb::IMessage<BehavioralContextInteraction>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BehavioralContextInteraction> _parser = new pb::MessageParser<BehavioralContextInteraction>(() => new BehavioralContextInteraction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BehavioralContextInteraction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ai.Inworld.Studio.V1Alpha.BehavioralContextsReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BehavioralContextInteraction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BehavioralContextInteraction(BehavioralContextInteraction other) : this() {
      interactionType_ = other.interactionType_;
      actions_ = other.actions_.Clone();
      uuid_ = other.uuid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BehavioralContextInteraction Clone() {
      return new BehavioralContextInteraction(this);
    }

    /// <summary>Field number for the "interaction_type" field.</summary>
    public const int InteractionTypeFieldNumber = 1;
    private global::Ai.Inworld.Studio.V1Alpha.BehavioralContextInteractionType interactionType_ = global::Ai.Inworld.Studio.V1Alpha.BehavioralContextInteractionType.Unspecified;
    /// <summary>
    /// The resource type to generate resource name for.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ai.Inworld.Studio.V1Alpha.BehavioralContextInteractionType InteractionType {
      get { return interactionType_; }
      set {
        interactionType_ = value;
      }
    }

    /// <summary>Field number for the "actions" field.</summary>
    public const int ActionsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Ai.Inworld.Studio.V1Alpha.BehavioralContextAction> _repeated_actions_codec
        = pb::FieldCodec.ForMessage(18, global::Ai.Inworld.Studio.V1Alpha.BehavioralContextAction.Parser);
    private readonly pbc::RepeatedField<global::Ai.Inworld.Studio.V1Alpha.BehavioralContextAction> actions_ = new pbc::RepeatedField<global::Ai.Inworld.Studio.V1Alpha.BehavioralContextAction>();
    /// <summary>
    /// Sequence of interactions to be executed.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ai.Inworld.Studio.V1Alpha.BehavioralContextAction> Actions {
      get { return actions_; }
    }

    /// <summary>Field number for the "uuid" field.</summary>
    public const int UuidFieldNumber = 3;
    private string uuid_ = "";
    /// <summary>
    /// Unique (throughout the entire service) universally unique identifier
    /// automatically generated by system.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Uuid {
      get { return uuid_; }
      set {
        uuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BehavioralContextInteraction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BehavioralContextInteraction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InteractionType != other.InteractionType) return false;
      if(!actions_.Equals(other.actions_)) return false;
      if (Uuid != other.Uuid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (InteractionType != global::Ai.Inworld.Studio.V1Alpha.BehavioralContextInteractionType.Unspecified) hash ^= InteractionType.GetHashCode();
      hash ^= actions_.GetHashCode();
      if (Uuid.Length != 0) hash ^= Uuid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (InteractionType != global::Ai.Inworld.Studio.V1Alpha.BehavioralContextInteractionType.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) InteractionType);
      }
      actions_.WriteTo(output, _repeated_actions_codec);
      if (Uuid.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Uuid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (InteractionType != global::Ai.Inworld.Studio.V1Alpha.BehavioralContextInteractionType.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) InteractionType);
      }
      actions_.WriteTo(ref output, _repeated_actions_codec);
      if (Uuid.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Uuid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (InteractionType != global::Ai.Inworld.Studio.V1Alpha.BehavioralContextInteractionType.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) InteractionType);
      }
      size += actions_.CalculateSize(_repeated_actions_codec);
      if (Uuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uuid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BehavioralContextInteraction other) {
      if (other == null) {
        return;
      }
      if (other.InteractionType != global::Ai.Inworld.Studio.V1Alpha.BehavioralContextInteractionType.Unspecified) {
        InteractionType = other.InteractionType;
      }
      actions_.Add(other.actions_);
      if (other.Uuid.Length != 0) {
        Uuid = other.Uuid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            InteractionType = (global::Ai.Inworld.Studio.V1Alpha.BehavioralContextInteractionType) input.ReadEnum();
            break;
          }
          case 18: {
            actions_.AddEntriesFrom(input, _repeated_actions_codec);
            break;
          }
          case 26: {
            Uuid = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            InteractionType = (global::Ai.Inworld.Studio.V1Alpha.BehavioralContextInteractionType) input.ReadEnum();
            break;
          }
          case 18: {
            actions_.AddEntriesFrom(ref input, _repeated_actions_codec);
            break;
          }
          case 26: {
            Uuid = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Behavioral context is an independent sequence of actions that may be triggered with a set of triggers.
  /// </summary>
  public sealed partial class BehavioralContext : pb::IMessage<BehavioralContext>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BehavioralContext> _parser = new pb::MessageParser<BehavioralContext>(() => new BehavioralContext());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BehavioralContext> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ai.Inworld.Studio.V1Alpha.BehavioralContextsReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BehavioralContext() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BehavioralContext(BehavioralContext other) : this() {
      name_ = other.name_;
      motivation_ = other.motivation_;
      properties_ = other.properties_ != null ? other.properties_.Clone() : null;
      triggers_ = other.triggers_.Clone();
      behavioralContextInteraction_ = other.behavioralContextInteraction_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BehavioralContext Clone() {
      return new BehavioralContext(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    /// Name of this context. Must be unique in the scope of a single brain.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "motivation" field.</summary>
    public const int MotivationFieldNumber = 2;
    private string motivation_ = "";
    /// <summary>
    /// Motivation, this character has during execution of this context.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Motivation {
      get { return motivation_; }
      set {
        motivation_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "properties" field.</summary>
    public const int PropertiesFieldNumber = 3;
    private global::Ai.Inworld.Studio.V1Alpha.BehavioralContextProperties properties_;
    /// <summary>
    /// Additional properties of the context.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ai.Inworld.Studio.V1Alpha.BehavioralContextProperties Properties {
      get { return properties_; }
      set {
        properties_ = value;
      }
    }

    /// <summary>Field number for the "triggers" field.</summary>
    public const int TriggersFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_triggers_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> triggers_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// Set of triggers, required to activate this context.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Triggers {
      get { return triggers_; }
    }

    /// <summary>Field number for the "behavioral_context_interaction" field.</summary>
    public const int BehavioralContextInteractionFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Ai.Inworld.Studio.V1Alpha.BehavioralContextInteraction> _repeated_behavioralContextInteraction_codec
        = pb::FieldCodec.ForMessage(42, global::Ai.Inworld.Studio.V1Alpha.BehavioralContextInteraction.Parser);
    private readonly pbc::RepeatedField<global::Ai.Inworld.Studio.V1Alpha.BehavioralContextInteraction> behavioralContextInteraction_ = new pbc::RepeatedField<global::Ai.Inworld.Studio.V1Alpha.BehavioralContextInteraction>();
    /// <summary>
    /// Set of actions
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ai.Inworld.Studio.V1Alpha.BehavioralContextInteraction> BehavioralContextInteraction {
      get { return behavioralContextInteraction_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BehavioralContext);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BehavioralContext other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Motivation != other.Motivation) return false;
      if (!object.Equals(Properties, other.Properties)) return false;
      if(!triggers_.Equals(other.triggers_)) return false;
      if(!behavioralContextInteraction_.Equals(other.behavioralContextInteraction_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Motivation.Length != 0) hash ^= Motivation.GetHashCode();
      if (properties_ != null) hash ^= Properties.GetHashCode();
      hash ^= triggers_.GetHashCode();
      hash ^= behavioralContextInteraction_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Motivation.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Motivation);
      }
      if (properties_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Properties);
      }
      triggers_.WriteTo(output, _repeated_triggers_codec);
      behavioralContextInteraction_.WriteTo(output, _repeated_behavioralContextInteraction_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Motivation.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Motivation);
      }
      if (properties_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Properties);
      }
      triggers_.WriteTo(ref output, _repeated_triggers_codec);
      behavioralContextInteraction_.WriteTo(ref output, _repeated_behavioralContextInteraction_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Motivation.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Motivation);
      }
      if (properties_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Properties);
      }
      size += triggers_.CalculateSize(_repeated_triggers_codec);
      size += behavioralContextInteraction_.CalculateSize(_repeated_behavioralContextInteraction_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BehavioralContext other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Motivation.Length != 0) {
        Motivation = other.Motivation;
      }
      if (other.properties_ != null) {
        if (properties_ == null) {
          Properties = new global::Ai.Inworld.Studio.V1Alpha.BehavioralContextProperties();
        }
        Properties.MergeFrom(other.Properties);
      }
      triggers_.Add(other.triggers_);
      behavioralContextInteraction_.Add(other.behavioralContextInteraction_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Motivation = input.ReadString();
            break;
          }
          case 26: {
            if (properties_ == null) {
              Properties = new global::Ai.Inworld.Studio.V1Alpha.BehavioralContextProperties();
            }
            input.ReadMessage(Properties);
            break;
          }
          case 34: {
            triggers_.AddEntriesFrom(input, _repeated_triggers_codec);
            break;
          }
          case 42: {
            behavioralContextInteraction_.AddEntriesFrom(input, _repeated_behavioralContextInteraction_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Motivation = input.ReadString();
            break;
          }
          case 26: {
            if (properties_ == null) {
              Properties = new global::Ai.Inworld.Studio.V1Alpha.BehavioralContextProperties();
            }
            input.ReadMessage(Properties);
            break;
          }
          case 34: {
            triggers_.AddEntriesFrom(ref input, _repeated_triggers_codec);
            break;
          }
          case 42: {
            behavioralContextInteraction_.AddEntriesFrom(ref input, _repeated_behavioralContextInteraction_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
