// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: pubsub/session_packets.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ai.Inworld.PubSub.Proxy {

  /// <summary>Holder for reflection information generated from pubsub/session_packets.proto</summary>
  public static partial class SessionPacketsReflection {

    #region Descriptor
    /// <summary>File descriptor for pubsub/session_packets.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SessionPacketsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxwdWJzdWIvc2Vzc2lvbl9wYWNrZXRzLnByb3RvEhFhaS5pbndvcmxkLnB1",
            "YnN1YiKkAgoNU2Vzc2lvblBhY2tldBISCgpzZXNzaW9uX2lkGAEgASgJEhIK",
            "CnJlcXVlc3RfaWQYAiABKAkSEgoKcGFja2V0X251bRgDIAEoDRI9CglkaXJl",
            "Y3Rpb24YBCABKA4yKi5haS5pbndvcmxkLnB1YnN1Yi5TZXNzaW9uUGFja2V0",
            "LkRpcmVjdGlvbhIRCgl0aW1lc3RhbXAYBSABKAQSDgoGYXBpa2V5GAYgASgJ",
            "Eg4KBnBhY2tldBgHIAEoDBISCgpiaWxsaW5nX2lkGAggASgJEhQKDHdvcmtz",
            "cGFjZV9pZBgJIAEoCRITCgtyZXNvdXJjZV9pZBgKIAEoCSImCglEaXJlY3Rp",
            "b24SCwoHSU5CT1VORBAAEgwKCE9VVEJPVU5EEAFCcwoXYWkuaW53b3JsZC5w",
            "dWJzdWIucHJveHlCEFByb3h5RXZlbnRzUHJvdG9QAVoqZ2l0aHViLmNvbS9p",
            "bndvcmxkLWFpL2lud29ybGQvcHVic3ViL3Byb3h5qgIXQWkuSW53b3JsZC5Q",
            "dWJTdWIuUHJveHliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ai.Inworld.PubSub.Proxy.SessionPacket), global::Ai.Inworld.PubSub.Proxy.SessionPacket.Parser, new[]{ "SessionId", "RequestId", "PacketNum", "Direction", "Timestamp", "Apikey", "Packet", "BillingId", "WorkspaceId", "ResourceId" }, null, new[]{ typeof(global::Ai.Inworld.PubSub.Proxy.SessionPacket.Types.Direction) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SessionPacket : pb::IMessage<SessionPacket>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SessionPacket> _parser = new pb::MessageParser<SessionPacket>(() => new SessionPacket());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SessionPacket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ai.Inworld.PubSub.Proxy.SessionPacketsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionPacket() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionPacket(SessionPacket other) : this() {
      sessionId_ = other.sessionId_;
      requestId_ = other.requestId_;
      packetNum_ = other.packetNum_;
      direction_ = other.direction_;
      timestamp_ = other.timestamp_;
      apikey_ = other.apikey_;
      packet_ = other.packet_;
      billingId_ = other.billingId_;
      workspaceId_ = other.workspaceId_;
      resourceId_ = other.resourceId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionPacket Clone() {
      return new SessionPacket(this);
    }

    /// <summary>Field number for the "session_id" field.</summary>
    public const int SessionIdFieldNumber = 1;
    private string sessionId_ = "";
    /// <summary>
    /// World engine session key
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SessionId {
      get { return sessionId_; }
      set {
        sessionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "request_id" field.</summary>
    public const int RequestIdFieldNumber = 2;
    private string requestId_ = "";
    /// <summary>
    /// Some ID of a particular request to open the session
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RequestId {
      get { return requestId_; }
      set {
        requestId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "packet_num" field.</summary>
    public const int PacketNumFieldNumber = 3;
    private uint packetNum_;
    /// <summary>
    /// Serial number of this packet in the request
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PacketNum {
      get { return packetNum_; }
      set {
        packetNum_ = value;
      }
    }

    /// <summary>Field number for the "direction" field.</summary>
    public const int DirectionFieldNumber = 4;
    private global::Ai.Inworld.PubSub.Proxy.SessionPacket.Types.Direction direction_ = global::Ai.Inworld.PubSub.Proxy.SessionPacket.Types.Direction.Inbound;
    /// <summary>
    /// IN = (from client to server) OUT = (from server to client)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ai.Inworld.PubSub.Proxy.SessionPacket.Types.Direction Direction {
      get { return direction_; }
      set {
        direction_ = value;
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 5;
    private ulong timestamp_;
    /// <summary>
    /// Unix time in milliseconds
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "apikey" field.</summary>
    public const int ApikeyFieldNumber = 6;
    private string apikey_ = "";
    /// <summary>
    /// API key which where used to authorize
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Apikey {
      get { return apikey_; }
      set {
        apikey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "packet" field.</summary>
    public const int PacketFieldNumber = 7;
    private pb::ByteString packet_ = pb::ByteString.Empty;
    /// <summary>
    /// Packet content
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Packet {
      get { return packet_; }
      set {
        packet_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "billing_id" field.</summary>
    public const int BillingIdFieldNumber = 8;
    private string billingId_ = "";
    /// <summary>
    /// Billing account ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BillingId {
      get { return billingId_; }
      set {
        billingId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "workspace_id" field.</summary>
    public const int WorkspaceIdFieldNumber = 9;
    private string workspaceId_ = "";
    /// <summary>
    /// Workspace name
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string WorkspaceId {
      get { return workspaceId_; }
      set {
        workspaceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "resource_id" field.</summary>
    public const int ResourceIdFieldNumber = 10;
    private string resourceId_ = "";
    /// <summary>
    /// Resource ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ResourceId {
      get { return resourceId_; }
      set {
        resourceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SessionPacket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SessionPacket other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SessionId != other.SessionId) return false;
      if (RequestId != other.RequestId) return false;
      if (PacketNum != other.PacketNum) return false;
      if (Direction != other.Direction) return false;
      if (Timestamp != other.Timestamp) return false;
      if (Apikey != other.Apikey) return false;
      if (Packet != other.Packet) return false;
      if (BillingId != other.BillingId) return false;
      if (WorkspaceId != other.WorkspaceId) return false;
      if (ResourceId != other.ResourceId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SessionId.Length != 0) hash ^= SessionId.GetHashCode();
      if (RequestId.Length != 0) hash ^= RequestId.GetHashCode();
      if (PacketNum != 0) hash ^= PacketNum.GetHashCode();
      if (Direction != global::Ai.Inworld.PubSub.Proxy.SessionPacket.Types.Direction.Inbound) hash ^= Direction.GetHashCode();
      if (Timestamp != 0UL) hash ^= Timestamp.GetHashCode();
      if (Apikey.Length != 0) hash ^= Apikey.GetHashCode();
      if (Packet.Length != 0) hash ^= Packet.GetHashCode();
      if (BillingId.Length != 0) hash ^= BillingId.GetHashCode();
      if (WorkspaceId.Length != 0) hash ^= WorkspaceId.GetHashCode();
      if (ResourceId.Length != 0) hash ^= ResourceId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SessionId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SessionId);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RequestId);
      }
      if (PacketNum != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(PacketNum);
      }
      if (Direction != global::Ai.Inworld.PubSub.Proxy.SessionPacket.Types.Direction.Inbound) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Direction);
      }
      if (Timestamp != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(Timestamp);
      }
      if (Apikey.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Apikey);
      }
      if (Packet.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(Packet);
      }
      if (BillingId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(BillingId);
      }
      if (WorkspaceId.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(WorkspaceId);
      }
      if (ResourceId.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(ResourceId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SessionId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SessionId);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RequestId);
      }
      if (PacketNum != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(PacketNum);
      }
      if (Direction != global::Ai.Inworld.PubSub.Proxy.SessionPacket.Types.Direction.Inbound) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Direction);
      }
      if (Timestamp != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(Timestamp);
      }
      if (Apikey.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Apikey);
      }
      if (Packet.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(Packet);
      }
      if (BillingId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(BillingId);
      }
      if (WorkspaceId.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(WorkspaceId);
      }
      if (ResourceId.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(ResourceId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SessionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionId);
      }
      if (RequestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestId);
      }
      if (PacketNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PacketNum);
      }
      if (Direction != global::Ai.Inworld.PubSub.Proxy.SessionPacket.Types.Direction.Inbound) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Direction);
      }
      if (Timestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Timestamp);
      }
      if (Apikey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Apikey);
      }
      if (Packet.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Packet);
      }
      if (BillingId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BillingId);
      }
      if (WorkspaceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WorkspaceId);
      }
      if (ResourceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResourceId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SessionPacket other) {
      if (other == null) {
        return;
      }
      if (other.SessionId.Length != 0) {
        SessionId = other.SessionId;
      }
      if (other.RequestId.Length != 0) {
        RequestId = other.RequestId;
      }
      if (other.PacketNum != 0) {
        PacketNum = other.PacketNum;
      }
      if (other.Direction != global::Ai.Inworld.PubSub.Proxy.SessionPacket.Types.Direction.Inbound) {
        Direction = other.Direction;
      }
      if (other.Timestamp != 0UL) {
        Timestamp = other.Timestamp;
      }
      if (other.Apikey.Length != 0) {
        Apikey = other.Apikey;
      }
      if (other.Packet.Length != 0) {
        Packet = other.Packet;
      }
      if (other.BillingId.Length != 0) {
        BillingId = other.BillingId;
      }
      if (other.WorkspaceId.Length != 0) {
        WorkspaceId = other.WorkspaceId;
      }
      if (other.ResourceId.Length != 0) {
        ResourceId = other.ResourceId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SessionId = input.ReadString();
            break;
          }
          case 18: {
            RequestId = input.ReadString();
            break;
          }
          case 24: {
            PacketNum = input.ReadUInt32();
            break;
          }
          case 32: {
            Direction = (global::Ai.Inworld.PubSub.Proxy.SessionPacket.Types.Direction) input.ReadEnum();
            break;
          }
          case 40: {
            Timestamp = input.ReadUInt64();
            break;
          }
          case 50: {
            Apikey = input.ReadString();
            break;
          }
          case 58: {
            Packet = input.ReadBytes();
            break;
          }
          case 66: {
            BillingId = input.ReadString();
            break;
          }
          case 74: {
            WorkspaceId = input.ReadString();
            break;
          }
          case 82: {
            ResourceId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SessionId = input.ReadString();
            break;
          }
          case 18: {
            RequestId = input.ReadString();
            break;
          }
          case 24: {
            PacketNum = input.ReadUInt32();
            break;
          }
          case 32: {
            Direction = (global::Ai.Inworld.PubSub.Proxy.SessionPacket.Types.Direction) input.ReadEnum();
            break;
          }
          case 40: {
            Timestamp = input.ReadUInt64();
            break;
          }
          case 50: {
            Apikey = input.ReadString();
            break;
          }
          case 58: {
            Packet = input.ReadBytes();
            break;
          }
          case 66: {
            BillingId = input.ReadString();
            break;
          }
          case 74: {
            WorkspaceId = input.ReadString();
            break;
          }
          case 82: {
            ResourceId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the SessionPacket message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Direction {
        [pbr::OriginalName("INBOUND")] Inbound = 0,
        [pbr::OriginalName("OUTBOUND")] Outbound = 1,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
