// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: voices.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ai.Inworld.Voices {

  /// <summary>Holder for reflection information generated from voices.proto</summary>
  public static partial class VoicesReflection {

    #region Descriptor
    /// <summary>File descriptor for voices.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VoicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgx2b2ljZXMucHJvdG8SEWFpLmlud29ybGQudm9pY2VzIuwDCgVWb2ljZRIQ",
            "CghiYXNlTmFtZRgBIAEoCRIsCgh0dHNfdHlwZRgCIAEoDjIaLmFpLmlud29y",
            "bGQudm9pY2VzLlRUU1R5cGUSKQoGZ2VuZGVyGAMgASgOMhkuYWkuaW53b3Js",
            "ZC52b2ljZXMuR2VuZGVyEg0KBXBpdGNoGAQgASgBEhUKDXNwZWFraW5nX3Jh",
            "dGUYBSABKAESIgoacm9ib3RpY192b2ljZV9maWx0ZXJfbGV2ZWwYBiABKAES",
            "SwoScGhvbmVtZXNfb3ZlcnJpZGVzGAcgAygLMi8uYWkuaW53b3JsZC52b2lj",
            "ZXMuVm9pY2UuUGhvbmVtZXNPdmVycmlkZXNFbnRyeRIjCgNhZ2UYCCABKA4y",
            "Fi5haS5pbndvcmxkLnZvaWNlcy5BZ2USSgoTZWxldmVubGFic19tZXRhZGF0",
            "YRhkIAEoCzIrLmFpLmlud29ybGQudm9pY2VzLlZvaWNlLkVsZXZlbkxhYnNN",
            "ZXRhZGF0YUgAGjgKFlBob25lbWVzT3ZlcnJpZGVzRW50cnkSCwoDa2V5GAEg",
            "ASgJEg0KBXZhbHVlGAIgASgJOgI4ARomChJFbGV2ZW5MYWJzTWV0YWRhdGES",
            "EAoIdm9pY2VfaWQYASABKAlCDgoMdHRzX21ldGFkYXRhKnAKBkdlbmRlchIc",
            "ChhWT0lDRV9HRU5ERVJfVU5TUEVDSUZJRUQQABIVChFWT0lDRV9HRU5ERVJf",
            "TUFMRRABEhcKE1ZPSUNFX0dFTkRFUl9GRU1BTEUQAhIYChRWT0lDRV9HRU5E",
            "RVJfTkVVVFJBTBADKmMKA0FnZRIZChVWT0lDRV9BR0VfVU5TUEVDSUZJRUQQ",
            "ABITCg9WT0lDRV9BR0VfWU9VTkcQARIZChVWT0lDRV9BR0VfTUlERExFX0FH",
            "RUQQAhIRCg1WT0lDRV9BR0VfT0xEEAMqVQoHVFRTVHlwZRIZChFUVFNfVFlQ",
            "RV9TVEFOREFSRBAAGgIIARIVChFUVFNfVFlQRV9BRFZBTkNFRBABEhgKFFRU",
            "U19UWVBFX0VMRVZFTl9MQUJTEAJCcgoRYWkuaW53b3JsZC52b2ljZXNCDlZv",
            "aWNlc1Byb3RvY29sWk1naXRodWIuY29tL2lud29ybGQtYWkvaW53b3JsZC9z",
            "ZXJ2aW5nL2dycGMtZ2F0ZXdheS9idWlsZC9wcm90by9lbmdpbmUvdjFhbHBo",
            "YWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Ai.Inworld.Voices.Gender), typeof(global::Ai.Inworld.Voices.Age), typeof(global::Ai.Inworld.Voices.TTSType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ai.Inworld.Voices.Voice), global::Ai.Inworld.Voices.Voice.Parser, new[]{ "BaseName", "TtsType", "Gender", "Pitch", "SpeakingRate", "RoboticVoiceFilterLevel", "PhonemesOverrides", "Age", "ElevenlabsMetadata" }, new[]{ "TtsMetadata" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, new pbr::GeneratedClrTypeInfo(typeof(global::Ai.Inworld.Voices.Voice.Types.ElevenLabsMetadata), global::Ai.Inworld.Voices.Voice.Types.ElevenLabsMetadata.Parser, new[]{ "VoiceId" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// There are 3 type of voice gender: m/f/n.
  /// </summary>
  public enum Gender {
    /// <summary>
    /// Gender not specified, should never be used.
    /// </summary>
    [pbr::OriginalName("VOICE_GENDER_UNSPECIFIED")] VoiceGenderUnspecified = 0,
    /// <summary>
    /// Male.
    /// </summary>
    [pbr::OriginalName("VOICE_GENDER_MALE")] VoiceGenderMale = 1,
    /// <summary>
    /// Female.
    /// </summary>
    [pbr::OriginalName("VOICE_GENDER_FEMALE")] VoiceGenderFemale = 2,
    /// <summary>
    /// Neutral.
    /// </summary>
    [pbr::OriginalName("VOICE_GENDER_NEUTRAL")] VoiceGenderNeutral = 3,
  }

  /// <summary>
  /// Age
  /// </summary>
  public enum Age {
    /// <summary>
    /// Gender not specified, should never be used.
    /// </summary>
    [pbr::OriginalName("VOICE_AGE_UNSPECIFIED")] VoiceAgeUnspecified = 0,
    /// <summary>
    /// Young
    /// </summary>
    [pbr::OriginalName("VOICE_AGE_YOUNG")] VoiceAgeYoung = 1,
    /// <summary>
    /// Middle aged
    /// </summary>
    [pbr::OriginalName("VOICE_AGE_MIDDLE_AGED")] VoiceAgeMiddleAged = 2,
    /// <summary>
    /// Old
    /// </summary>
    [pbr::OriginalName("VOICE_AGE_OLD")] VoiceAgeOld = 3,
  }

  /// <summary>
  /// TTS types.
  /// </summary>
  public enum TTSType {
    /// <summary>
    /// Means GOOGLE.
    /// </summary>
    [pbr::OriginalName("TTS_TYPE_STANDARD")] Standard = 0,
    /// <summary>
    /// Means INWORLD.
    /// </summary>
    [pbr::OriginalName("TTS_TYPE_ADVANCED")] Advanced = 1,
    /// <summary>
    /// Means ELEVEN_LABS.
    /// </summary>
    [pbr::OriginalName("TTS_TYPE_ELEVEN_LABS")] ElevenLabs = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Voice structure.
  /// </summary>
  public sealed partial class Voice : pb::IMessage<Voice>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Voice> _parser = new pb::MessageParser<Voice>(() => new Voice());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Voice> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ai.Inworld.Voices.VoicesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Voice() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Voice(Voice other) : this() {
      baseName_ = other.baseName_;
      ttsType_ = other.ttsType_;
      gender_ = other.gender_;
      pitch_ = other.pitch_;
      speakingRate_ = other.speakingRate_;
      roboticVoiceFilterLevel_ = other.roboticVoiceFilterLevel_;
      phonemesOverrides_ = other.phonemesOverrides_.Clone();
      age_ = other.age_;
      switch (other.TtsMetadataCase) {
        case TtsMetadataOneofCase.ElevenlabsMetadata:
          ElevenlabsMetadata = other.ElevenlabsMetadata.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Voice Clone() {
      return new Voice(this);
    }

    /// <summary>Field number for the "baseName" field.</summary>
    public const int BaseNameFieldNumber = 1;
    private string baseName_ = "";
    /// <summary>
    /// Voice base name.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BaseName {
      get { return baseName_; }
      set {
        baseName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tts_type" field.</summary>
    public const int TtsTypeFieldNumber = 2;
    private global::Ai.Inworld.Voices.TTSType ttsType_ = global::Ai.Inworld.Voices.TTSType.Standard;
    /// <summary>
    /// TTS type. Default = STANDARD.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ai.Inworld.Voices.TTSType TtsType {
      get { return ttsType_; }
      set {
        ttsType_ = value;
      }
    }

    /// <summary>Field number for the "gender" field.</summary>
    public const int GenderFieldNumber = 3;
    private global::Ai.Inworld.Voices.Gender gender_ = global::Ai.Inworld.Voices.Gender.VoiceGenderUnspecified;
    /// <summary>
    /// Voice gender. Default = MALE.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ai.Inworld.Voices.Gender Gender {
      get { return gender_; }
      set {
        gender_ = value;
      }
    }

    /// <summary>Field number for the "pitch" field.</summary>
    public const int PitchFieldNumber = 4;
    private double pitch_;
    /// <summary>
    /// Voice pitch. Default = 1, range = [-10, 10].
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Pitch {
      get { return pitch_; }
      set {
        pitch_ = value;
      }
    }

    /// <summary>Field number for the "speaking_rate" field.</summary>
    public const int SpeakingRateFieldNumber = 5;
    private double speakingRate_;
    /// <summary>
    /// Speaking rate Default = 1, range = [0.25, 4].
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double SpeakingRate {
      get { return speakingRate_; }
      set {
        speakingRate_ = value;
      }
    }

    /// <summary>Field number for the "robotic_voice_filter_level" field.</summary>
    public const int RoboticVoiceFilterLevelFieldNumber = 6;
    private double roboticVoiceFilterLevel_;
    /// <summary>
    /// Robotic filter level. Default = 0, range = [0, 5].
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double RoboticVoiceFilterLevel {
      get { return roboticVoiceFilterLevel_; }
      set {
        roboticVoiceFilterLevel_ = value;
      }
    }

    /// <summary>Field number for the "phonemes_overrides" field.</summary>
    public const int PhonemesOverridesFieldNumber = 7;
    private static readonly pbc::MapField<string, string>.Codec _map_phonemesOverrides_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 58);
    private readonly pbc::MapField<string, string> phonemesOverrides_ = new pbc::MapField<string, string>();
    /// <summary>
    /// Phonemes overrides (text and ipa string to map text to)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> PhonemesOverrides {
      get { return phonemesOverrides_; }
    }

    /// <summary>Field number for the "age" field.</summary>
    public const int AgeFieldNumber = 8;
    private global::Ai.Inworld.Voices.Age age_ = global::Ai.Inworld.Voices.Age.VoiceAgeUnspecified;
    /// <summary>
    /// Voice age
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ai.Inworld.Voices.Age Age {
      get { return age_; }
      set {
        age_ = value;
      }
    }

    /// <summary>Field number for the "elevenlabs_metadata" field.</summary>
    public const int ElevenlabsMetadataFieldNumber = 100;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ai.Inworld.Voices.Voice.Types.ElevenLabsMetadata ElevenlabsMetadata {
      get { return ttsMetadataCase_ == TtsMetadataOneofCase.ElevenlabsMetadata ? (global::Ai.Inworld.Voices.Voice.Types.ElevenLabsMetadata) ttsMetadata_ : null; }
      set {
        ttsMetadata_ = value;
        ttsMetadataCase_ = value == null ? TtsMetadataOneofCase.None : TtsMetadataOneofCase.ElevenlabsMetadata;
      }
    }

    private object ttsMetadata_;
    /// <summary>Enum of possible cases for the "tts_metadata" oneof.</summary>
    public enum TtsMetadataOneofCase {
      None = 0,
      ElevenlabsMetadata = 100,
    }
    private TtsMetadataOneofCase ttsMetadataCase_ = TtsMetadataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TtsMetadataOneofCase TtsMetadataCase {
      get { return ttsMetadataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTtsMetadata() {
      ttsMetadataCase_ = TtsMetadataOneofCase.None;
      ttsMetadata_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Voice);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Voice other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BaseName != other.BaseName) return false;
      if (TtsType != other.TtsType) return false;
      if (Gender != other.Gender) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Pitch, other.Pitch)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(SpeakingRate, other.SpeakingRate)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(RoboticVoiceFilterLevel, other.RoboticVoiceFilterLevel)) return false;
      if (!PhonemesOverrides.Equals(other.PhonemesOverrides)) return false;
      if (Age != other.Age) return false;
      if (!object.Equals(ElevenlabsMetadata, other.ElevenlabsMetadata)) return false;
      if (TtsMetadataCase != other.TtsMetadataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BaseName.Length != 0) hash ^= BaseName.GetHashCode();
      if (TtsType != global::Ai.Inworld.Voices.TTSType.Standard) hash ^= TtsType.GetHashCode();
      if (Gender != global::Ai.Inworld.Voices.Gender.VoiceGenderUnspecified) hash ^= Gender.GetHashCode();
      if (Pitch != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Pitch);
      if (SpeakingRate != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(SpeakingRate);
      if (RoboticVoiceFilterLevel != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(RoboticVoiceFilterLevel);
      hash ^= PhonemesOverrides.GetHashCode();
      if (Age != global::Ai.Inworld.Voices.Age.VoiceAgeUnspecified) hash ^= Age.GetHashCode();
      if (ttsMetadataCase_ == TtsMetadataOneofCase.ElevenlabsMetadata) hash ^= ElevenlabsMetadata.GetHashCode();
      hash ^= (int) ttsMetadataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BaseName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(BaseName);
      }
      if (TtsType != global::Ai.Inworld.Voices.TTSType.Standard) {
        output.WriteRawTag(16);
        output.WriteEnum((int) TtsType);
      }
      if (Gender != global::Ai.Inworld.Voices.Gender.VoiceGenderUnspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Gender);
      }
      if (Pitch != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Pitch);
      }
      if (SpeakingRate != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(SpeakingRate);
      }
      if (RoboticVoiceFilterLevel != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(RoboticVoiceFilterLevel);
      }
      phonemesOverrides_.WriteTo(output, _map_phonemesOverrides_codec);
      if (Age != global::Ai.Inworld.Voices.Age.VoiceAgeUnspecified) {
        output.WriteRawTag(64);
        output.WriteEnum((int) Age);
      }
      if (ttsMetadataCase_ == TtsMetadataOneofCase.ElevenlabsMetadata) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(ElevenlabsMetadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BaseName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(BaseName);
      }
      if (TtsType != global::Ai.Inworld.Voices.TTSType.Standard) {
        output.WriteRawTag(16);
        output.WriteEnum((int) TtsType);
      }
      if (Gender != global::Ai.Inworld.Voices.Gender.VoiceGenderUnspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Gender);
      }
      if (Pitch != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Pitch);
      }
      if (SpeakingRate != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(SpeakingRate);
      }
      if (RoboticVoiceFilterLevel != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(RoboticVoiceFilterLevel);
      }
      phonemesOverrides_.WriteTo(ref output, _map_phonemesOverrides_codec);
      if (Age != global::Ai.Inworld.Voices.Age.VoiceAgeUnspecified) {
        output.WriteRawTag(64);
        output.WriteEnum((int) Age);
      }
      if (ttsMetadataCase_ == TtsMetadataOneofCase.ElevenlabsMetadata) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(ElevenlabsMetadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BaseName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BaseName);
      }
      if (TtsType != global::Ai.Inworld.Voices.TTSType.Standard) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TtsType);
      }
      if (Gender != global::Ai.Inworld.Voices.Gender.VoiceGenderUnspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Gender);
      }
      if (Pitch != 0D) {
        size += 1 + 8;
      }
      if (SpeakingRate != 0D) {
        size += 1 + 8;
      }
      if (RoboticVoiceFilterLevel != 0D) {
        size += 1 + 8;
      }
      size += phonemesOverrides_.CalculateSize(_map_phonemesOverrides_codec);
      if (Age != global::Ai.Inworld.Voices.Age.VoiceAgeUnspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Age);
      }
      if (ttsMetadataCase_ == TtsMetadataOneofCase.ElevenlabsMetadata) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ElevenlabsMetadata);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Voice other) {
      if (other == null) {
        return;
      }
      if (other.BaseName.Length != 0) {
        BaseName = other.BaseName;
      }
      if (other.TtsType != global::Ai.Inworld.Voices.TTSType.Standard) {
        TtsType = other.TtsType;
      }
      if (other.Gender != global::Ai.Inworld.Voices.Gender.VoiceGenderUnspecified) {
        Gender = other.Gender;
      }
      if (other.Pitch != 0D) {
        Pitch = other.Pitch;
      }
      if (other.SpeakingRate != 0D) {
        SpeakingRate = other.SpeakingRate;
      }
      if (other.RoboticVoiceFilterLevel != 0D) {
        RoboticVoiceFilterLevel = other.RoboticVoiceFilterLevel;
      }
      phonemesOverrides_.Add(other.phonemesOverrides_);
      if (other.Age != global::Ai.Inworld.Voices.Age.VoiceAgeUnspecified) {
        Age = other.Age;
      }
      switch (other.TtsMetadataCase) {
        case TtsMetadataOneofCase.ElevenlabsMetadata:
          if (ElevenlabsMetadata == null) {
            ElevenlabsMetadata = new global::Ai.Inworld.Voices.Voice.Types.ElevenLabsMetadata();
          }
          ElevenlabsMetadata.MergeFrom(other.ElevenlabsMetadata);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            BaseName = input.ReadString();
            break;
          }
          case 16: {
            TtsType = (global::Ai.Inworld.Voices.TTSType) input.ReadEnum();
            break;
          }
          case 24: {
            Gender = (global::Ai.Inworld.Voices.Gender) input.ReadEnum();
            break;
          }
          case 33: {
            Pitch = input.ReadDouble();
            break;
          }
          case 41: {
            SpeakingRate = input.ReadDouble();
            break;
          }
          case 49: {
            RoboticVoiceFilterLevel = input.ReadDouble();
            break;
          }
          case 58: {
            phonemesOverrides_.AddEntriesFrom(input, _map_phonemesOverrides_codec);
            break;
          }
          case 64: {
            Age = (global::Ai.Inworld.Voices.Age) input.ReadEnum();
            break;
          }
          case 802: {
            global::Ai.Inworld.Voices.Voice.Types.ElevenLabsMetadata subBuilder = new global::Ai.Inworld.Voices.Voice.Types.ElevenLabsMetadata();
            if (ttsMetadataCase_ == TtsMetadataOneofCase.ElevenlabsMetadata) {
              subBuilder.MergeFrom(ElevenlabsMetadata);
            }
            input.ReadMessage(subBuilder);
            ElevenlabsMetadata = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            BaseName = input.ReadString();
            break;
          }
          case 16: {
            TtsType = (global::Ai.Inworld.Voices.TTSType) input.ReadEnum();
            break;
          }
          case 24: {
            Gender = (global::Ai.Inworld.Voices.Gender) input.ReadEnum();
            break;
          }
          case 33: {
            Pitch = input.ReadDouble();
            break;
          }
          case 41: {
            SpeakingRate = input.ReadDouble();
            break;
          }
          case 49: {
            RoboticVoiceFilterLevel = input.ReadDouble();
            break;
          }
          case 58: {
            phonemesOverrides_.AddEntriesFrom(ref input, _map_phonemesOverrides_codec);
            break;
          }
          case 64: {
            Age = (global::Ai.Inworld.Voices.Age) input.ReadEnum();
            break;
          }
          case 802: {
            global::Ai.Inworld.Voices.Voice.Types.ElevenLabsMetadata subBuilder = new global::Ai.Inworld.Voices.Voice.Types.ElevenLabsMetadata();
            if (ttsMetadataCase_ == TtsMetadataOneofCase.ElevenlabsMetadata) {
              subBuilder.MergeFrom(ElevenlabsMetadata);
            }
            input.ReadMessage(subBuilder);
            ElevenlabsMetadata = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Voice message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// ElevenLabs Metadata
      /// </summary>
      public sealed partial class ElevenLabsMetadata : pb::IMessage<ElevenLabsMetadata>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<ElevenLabsMetadata> _parser = new pb::MessageParser<ElevenLabsMetadata>(() => new ElevenLabsMetadata());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<ElevenLabsMetadata> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Ai.Inworld.Voices.Voice.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ElevenLabsMetadata() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ElevenLabsMetadata(ElevenLabsMetadata other) : this() {
          voiceId_ = other.voiceId_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ElevenLabsMetadata Clone() {
          return new ElevenLabsMetadata(this);
        }

        /// <summary>Field number for the "voice_id" field.</summary>
        public const int VoiceIdFieldNumber = 1;
        private string voiceId_ = "";
        /// <summary>
        /// Voice id
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string VoiceId {
          get { return voiceId_; }
          set {
            voiceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as ElevenLabsMetadata);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(ElevenLabsMetadata other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (VoiceId != other.VoiceId) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (VoiceId.Length != 0) hash ^= VoiceId.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (VoiceId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(VoiceId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (VoiceId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(VoiceId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (VoiceId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(VoiceId);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(ElevenLabsMetadata other) {
          if (other == null) {
            return;
          }
          if (other.VoiceId.Length != 0) {
            VoiceId = other.VoiceId;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                VoiceId = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                VoiceId = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
