// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ai/inworld/studio/v1alpha/tokens.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Ai.Inworld.Studio.V1Alpha {
  /// <summary>
  /// Service to generate JWT
  /// </summary>
  public static partial class Tokens
  {
    static readonly string __ServiceName = "ai.inworld.studio.v1alpha.Tokens";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ai.Inworld.Studio.V1Alpha.GenerateSessionTokenRequest> __Marshaller_ai_inworld_studio_v1alpha_GenerateSessionTokenRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ai.Inworld.Studio.V1Alpha.GenerateSessionTokenRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ai.Inworld.Studio.V1Alpha.SessionAccessToken> __Marshaller_ai_inworld_studio_v1alpha_SessionAccessToken = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ai.Inworld.Studio.V1Alpha.SessionAccessToken.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ai.Inworld.Studio.V1Alpha.GenerateDefaultSessionTokenRequest> __Marshaller_ai_inworld_studio_v1alpha_GenerateDefaultSessionTokenRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ai.Inworld.Studio.V1Alpha.GenerateDefaultSessionTokenRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ai.Inworld.Studio.V1Alpha.GenerateSessionTokenRequest, global::Ai.Inworld.Studio.V1Alpha.SessionAccessToken> __Method_GenerateSessionToken = new grpc::Method<global::Ai.Inworld.Studio.V1Alpha.GenerateSessionTokenRequest, global::Ai.Inworld.Studio.V1Alpha.SessionAccessToken>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GenerateSessionToken",
        __Marshaller_ai_inworld_studio_v1alpha_GenerateSessionTokenRequest,
        __Marshaller_ai_inworld_studio_v1alpha_SessionAccessToken);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ai.Inworld.Studio.V1Alpha.GenerateDefaultSessionTokenRequest, global::Ai.Inworld.Studio.V1Alpha.SessionAccessToken> __Method_GenerateDefaultSessionToken = new grpc::Method<global::Ai.Inworld.Studio.V1Alpha.GenerateDefaultSessionTokenRequest, global::Ai.Inworld.Studio.V1Alpha.SessionAccessToken>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GenerateDefaultSessionToken",
        __Marshaller_ai_inworld_studio_v1alpha_GenerateDefaultSessionTokenRequest,
        __Marshaller_ai_inworld_studio_v1alpha_SessionAccessToken);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Ai.Inworld.Studio.V1Alpha.TokensReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Tokens</summary>
    [grpc::BindServiceMethod(typeof(Tokens), "BindService")]
    public abstract partial class TokensBase
    {
      /// <summary>
      /// Generates a JWT to access the world engine API with a given API key
      /// This method is meant to be used by end-user applications with API keys + secret
      /// A valid HMAC-SHA signature matching the API key in the request should be provided as authorization
      /// DEPRECATED: Runtime tokens are generated by the proxy-auth service
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ai.Inworld.Studio.V1Alpha.SessionAccessToken> GenerateSessionToken(global::Ai.Inworld.Studio.V1Alpha.GenerateSessionTokenRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Generates a JWT with the default API key for the given workspace
      /// This method is meant to be used by UI tools with user authorization such as Google or Oculus
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ai.Inworld.Studio.V1Alpha.SessionAccessToken> GenerateDefaultSessionToken(global::Ai.Inworld.Studio.V1Alpha.GenerateDefaultSessionTokenRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Tokens</summary>
    public partial class TokensClient : grpc::ClientBase<TokensClient>
    {
      /// <summary>Creates a new client for Tokens</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public TokensClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Tokens that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public TokensClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected TokensClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected TokensClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Generates a JWT to access the world engine API with a given API key
      /// This method is meant to be used by end-user applications with API keys + secret
      /// A valid HMAC-SHA signature matching the API key in the request should be provided as authorization
      /// DEPRECATED: Runtime tokens are generated by the proxy-auth service
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ai.Inworld.Studio.V1Alpha.SessionAccessToken GenerateSessionToken(global::Ai.Inworld.Studio.V1Alpha.GenerateSessionTokenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GenerateSessionToken(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates a JWT to access the world engine API with a given API key
      /// This method is meant to be used by end-user applications with API keys + secret
      /// A valid HMAC-SHA signature matching the API key in the request should be provided as authorization
      /// DEPRECATED: Runtime tokens are generated by the proxy-auth service
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ai.Inworld.Studio.V1Alpha.SessionAccessToken GenerateSessionToken(global::Ai.Inworld.Studio.V1Alpha.GenerateSessionTokenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GenerateSessionToken, null, options, request);
      }
      /// <summary>
      /// Generates a JWT to access the world engine API with a given API key
      /// This method is meant to be used by end-user applications with API keys + secret
      /// A valid HMAC-SHA signature matching the API key in the request should be provided as authorization
      /// DEPRECATED: Runtime tokens are generated by the proxy-auth service
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ai.Inworld.Studio.V1Alpha.SessionAccessToken> GenerateSessionTokenAsync(global::Ai.Inworld.Studio.V1Alpha.GenerateSessionTokenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GenerateSessionTokenAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates a JWT to access the world engine API with a given API key
      /// This method is meant to be used by end-user applications with API keys + secret
      /// A valid HMAC-SHA signature matching the API key in the request should be provided as authorization
      /// DEPRECATED: Runtime tokens are generated by the proxy-auth service
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ai.Inworld.Studio.V1Alpha.SessionAccessToken> GenerateSessionTokenAsync(global::Ai.Inworld.Studio.V1Alpha.GenerateSessionTokenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GenerateSessionToken, null, options, request);
      }
      /// <summary>
      /// Generates a JWT with the default API key for the given workspace
      /// This method is meant to be used by UI tools with user authorization such as Google or Oculus
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ai.Inworld.Studio.V1Alpha.SessionAccessToken GenerateDefaultSessionToken(global::Ai.Inworld.Studio.V1Alpha.GenerateDefaultSessionTokenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GenerateDefaultSessionToken(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates a JWT with the default API key for the given workspace
      /// This method is meant to be used by UI tools with user authorization such as Google or Oculus
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ai.Inworld.Studio.V1Alpha.SessionAccessToken GenerateDefaultSessionToken(global::Ai.Inworld.Studio.V1Alpha.GenerateDefaultSessionTokenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GenerateDefaultSessionToken, null, options, request);
      }
      /// <summary>
      /// Generates a JWT with the default API key for the given workspace
      /// This method is meant to be used by UI tools with user authorization such as Google or Oculus
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ai.Inworld.Studio.V1Alpha.SessionAccessToken> GenerateDefaultSessionTokenAsync(global::Ai.Inworld.Studio.V1Alpha.GenerateDefaultSessionTokenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GenerateDefaultSessionTokenAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates a JWT with the default API key for the given workspace
      /// This method is meant to be used by UI tools with user authorization such as Google or Oculus
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ai.Inworld.Studio.V1Alpha.SessionAccessToken> GenerateDefaultSessionTokenAsync(global::Ai.Inworld.Studio.V1Alpha.GenerateDefaultSessionTokenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GenerateDefaultSessionToken, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override TokensClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TokensClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(TokensBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GenerateSessionToken, serviceImpl.GenerateSessionToken)
          .AddMethod(__Method_GenerateDefaultSessionToken, serviceImpl.GenerateDefaultSessionToken).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, TokensBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GenerateSessionToken, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ai.Inworld.Studio.V1Alpha.GenerateSessionTokenRequest, global::Ai.Inworld.Studio.V1Alpha.SessionAccessToken>(serviceImpl.GenerateSessionToken));
      serviceBinder.AddMethod(__Method_GenerateDefaultSessionToken, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ai.Inworld.Studio.V1Alpha.GenerateDefaultSessionTokenRequest, global::Ai.Inworld.Studio.V1Alpha.SessionAccessToken>(serviceImpl.GenerateDefaultSessionToken));
    }

  }
}
#endregion
